### PR TITLE
[WIP] Analysis Script for Calculations

### PR DESCRIPTION
**Pull request by attack68**
Please review the analysis and merge to master if you agree the pipeline and choice of execution.

### CODE REVIEW

**Comment by albins** [comment]
I'm ready to merge this once Issue #6 with the CSV export is done!

**Comment by attack68** [comment]
Output should now return correct results and CSV is using saveAsTextFile().
We can perform a test and merge on success

**Comment by albins** [comment]
Excellent, I'll test it today and merge it when it works!

**Comment by albins** [comment]
Seems to work fine!

Closes #6

**Pull request merged**
